/*
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2.0,
 * as published by the Free Software Foundation.
 *
 * This program is also distributed with certain software (including
 * but not limited to OpenSSL) that is licensed under separate terms, as
 * designated in a particular file or component or in included license
 * documentation.  The authors of MySQL hereby grant you an additional
 * permission to link the program and your derivative works with the
 * separately licensed software that they have included with MySQL.
 * This program is distributed in the hope that it will be useful,  but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 * the GNU General Public License, version 2.0, for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

export enum ShellAPIGui {
    //  Begin auto generated API names
    GuiClusterIsGuiModuleBackend = "gui.cluster.is_gui_module_backend",
    GuiClusterGetGuiModuleDisplayInfo = "gui.cluster.get_gui_module_display_info",
    GuiCoreSetLogLevel = "gui.core.set_log_level",
    GuiCoreGetLogLevel = "gui.core.get_log_level",
    GuiCoreListFiles = "gui.core.list_files",
    GuiCoreCreateFile = "gui.core.create_file",
    GuiCoreValidatePath = "gui.core.validate_path",
    GuiCoreGetBackendInformation = "gui.core.get_backend_information",
    GuiCoreIsShellWebCertificateInstalled = "gui.core.is_shell_web_certificate_installed",
    GuiCoreInstallShellWebCertificate = "gui.core.install_shell_web_certificate",
    GuiCoreRemoveShellWebCertificate = "gui.core.remove_shell_web_certificate",
    GuiDbconnectionsAddDbConnection = "gui.dbconnections.add_db_connection",
    GuiDbconnectionsUpdateDbConnection = "gui.dbconnections.update_db_connection",
    GuiDbconnectionsRemoveDbConnection = "gui.dbconnections.remove_db_connection",
    GuiDbconnectionsListDbConnections = "gui.dbconnections.list_db_connections",
    GuiDbconnectionsGetDbConnection = "gui.dbconnections.get_db_connection",
    GuiDbconnectionsGetDbTypes = "gui.dbconnections.get_db_types",
    GuiDbconnectionsSetCredential = "gui.dbconnections.set_credential",
    GuiDbconnectionsDeleteCredential = "gui.dbconnections.delete_credential",
    GuiDbconnectionsListCredentials = "gui.dbconnections.list_credentials",
    GuiDbconnectionsTestConnection = "gui.dbconnections.test_connection",
    GuiDbconnectionsMoveConnection = "gui.dbconnections.move_connection",
    GuiMdsIsGuiModuleBackend = "gui.mds.is_gui_module_backend",
    GuiMdsGetGuiModuleDisplayInfo = "gui.mds.get_gui_module_display_info",
    GuiModelerIsGuiModuleBackend = "gui.modeler.is_gui_module_backend",
    GuiModelerGetGuiModuleDisplayInfo = "gui.modeler.get_gui_module_display_info",
    GuiShellIsGuiModuleBackend = "gui.shell.is_gui_module_backend",
    GuiShellGetGuiModuleDisplayInfo = "gui.shell.get_gui_module_display_info",
    GuiShellStartSession = "gui.shell.start_session",
    GuiShellCloseSession = "gui.shell.close_session",
    GuiShellExecute = "gui.shell.execute",
    GuiShellComplete = "gui.shell.complete",
    GuiShellKillTask = "gui.shell.kill_task",
    GuiDbGetObjectsTypes = "gui.db.get_objects_types",
    GuiDbGetCatalogObjectNames = "gui.db.get_catalog_object_names",
    GuiDbGetSchemaObjectNames = "gui.db.get_schema_object_names",
    GuiDbGetTableObjectNames = "gui.db.get_table_object_names",
    GuiDbGetCatalogObject = "gui.db.get_catalog_object",
    GuiDbGetSchemaObject = "gui.db.get_schema_object",
    GuiDbGetTableObject = "gui.db.get_table_object",
    GuiDbStartSession = "gui.db.start_session",
    GuiDbCloseSession = "gui.db.close_session",
    GuiDbReconnect = "gui.db.reconnect",
    GuiSqleditorIsGuiModuleBackend = "gui.sqleditor.is_gui_module_backend",
    GuiSqleditorGetGuiModuleDisplayInfo = "gui.sqleditor.get_gui_module_display_info",
    GuiSqleditorStartSession = "gui.sqleditor.start_session",
    GuiSqleditorCloseSession = "gui.sqleditor.close_session",
    GuiSqleditorOpenConnection = "gui.sqleditor.open_connection",
    GuiSqleditorReconnect = "gui.sqleditor.reconnect",
    GuiSqleditorExecute = "gui.sqleditor.execute",
    GuiSqleditorKillQuery = "gui.sqleditor.kill_query",
    GuiSqleditorGetCurrentSchema = "gui.sqleditor.get_current_schema",
    GuiSqleditorSetCurrentSchema = "gui.sqleditor.set_current_schema",
    GuiSqleditorGetAutoCommit = "gui.sqleditor.get_auto_commit",
    GuiSqleditorSetAutoCommit = "gui.sqleditor.set_auto_commit",
    GuiUsersCreateUser = "gui.users.create_user",
    GuiUsersSetAllowedHosts = "gui.users.set_allowed_hosts",
    GuiUsersDeleteUser = "gui.users.delete_user",
    GuiUsersGrantRole = "gui.users.grant_role",
    GuiUsersGetUserId = "gui.users.get_user_id",
    GuiUsersListUsers = "gui.users.list_users",
    GuiUsersListUserRoles = "gui.users.list_user_roles",
    GuiUsersListRoles = "gui.users.list_roles",
    GuiUsersListRolePrivileges = "gui.users.list_role_privileges",
    GuiUsersListUserPrivileges = "gui.users.list_user_privileges",
    GuiUsersGetGuiModuleList = "gui.users.get_gui_module_list",
    GuiUsersListProfiles = "gui.users.list_profiles",
    GuiUsersGetProfile = "gui.users.get_profile",
    GuiUsersUpdateProfile = "gui.users.update_profile",
    GuiUsersAddProfile = "gui.users.add_profile",
    GuiUsersDeleteProfile = "gui.users.delete_profile",
    GuiUsersGetDefaultProfile = "gui.users.get_default_profile",
    GuiUsersSetDefaultProfile = "gui.users.set_default_profile",
    GuiUsersSetCurrentProfile = "gui.users.set_current_profile",
    GuiUsersListUserGroups = "gui.users.list_user_groups",
    GuiUsersCreateUserGroup = "gui.users.create_user_group",
    GuiUsersAddUserToGroup = "gui.users.add_user_to_group",
    GuiUsersRemoveUserFromGroup = "gui.users.remove_user_from_group",
    GuiUsersUpdateUserGroup = "gui.users.update_user_group",
    GuiUsersRemoveUserGroup = "gui.users.remove_user_group",
    GuiDebuggerIsGuiModuleBackend = "gui.debugger.is_gui_module_backend",
    GuiDebuggerGetGuiModuleDisplayInfo = "gui.debugger.get_gui_module_display_info",
    GuiDebuggerGetScripts = "gui.debugger.get_scripts",
    GuiDebuggerGetScriptContent = "gui.debugger.get_script_content",
    GuiModulesAddData = "gui.modules.add_data",
    GuiModulesListData = "gui.modules.list_data",
    GuiModulesGetDataContent = "gui.modules.get_data_content",
    GuiModulesShareDataToUserGroup = "gui.modules.share_data_to_user_group",
    GuiModulesAddDataToProfile = "gui.modules.add_data_to_profile",
    GuiModulesUpdateData = "gui.modules.update_data",
    GuiModulesDeleteData = "gui.modules.delete_data",
    GuiModulesListDataCategories = "gui.modules.list_data_categories",
    GuiModulesAddDataCategory = "gui.modules.add_data_category",
    GuiModulesRemoveDataCategory = "gui.modules.remove_data_category",
    GuiModulesGetDataCategoryId = "gui.modules.get_data_category_id",
    GuiModulesCreateProfileDataTree = "gui.modules.create_profile_data_tree",
    GuiModulesGetProfileDataTree = "gui.modules.get_profile_data_tree",
    GuiModulesCreateUserGroupDataTree = "gui.modules.create_user_group_data_tree",
    GuiModulesGetUserGroupDataTree = "gui.modules.get_user_group_data_tree",
    GuiModulesGetProfileTreeIdentifiers = "gui.modules.get_profile_tree_identifiers",
    GuiModulesMoveData = "gui.modules.move_data",
    GuiInfo = "gui.info",
    GuiVersion = "gui.version",
    //  End auto generated API names
}
