/*
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2.0,
 * as published by the Free Software Foundation.
 *
 * This program is designed to work with certain software (including
 * but not limited to OpenSSL) that is licensed under separate terms, as
 * designated in a particular file or component or in included license
 * documentation.  The authors of MySQL hereby grant you an additional
 * permission to link the program and your derivative works with the
 * separately licensed software that they have either included with
 * the program or referenced in the documentation.
 *
 * This program is distributed in the hope that it will be useful,  but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 * the GNU General Public License, version 2.0, for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

/* spell-checker: disable */

export enum Codicon {
    Undefined,
    Account,
    ActivateBreakpoints,
    Add,
    Alert,
    Archive,
    Array,
    ArrowBoth,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowSmallDown,
    ArrowSmallLeft,
    ArrowSmallRight,
    ArrowSmallUp,
    ArrowUp,
    Beaker,
    Bell,
    BellDot,
    Bold,
    Book,
    Bookmark,
    Briefcase,
    Broadcast,
    Browser,
    Bug,
    Calendar,
    CallIncoming,
    CaseSensitive,
    Check,
    CheckAll,
    Checklist,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChromeClose,
    ChromeMaximize,
    ChromeMinimize,
    ChromeRestore,
    CircleFilled,
    CircleLargeFilled,
    CircleLargeOutline,
    CircleOutline,
    CircleSlash,
    CircuitBoard,
    ClearAll,
    Clippy,
    Clock,
    Clone,
    Close,
    CloseAll,
    CloseDirty,
    Cloud,
    CloudDownload,
    CloudUpload,
    Code,
    CollapseAll,
    ColorMode,
    Combine,
    Comment,
    CommentAdd,
    CommentDiscussion,
    CompareChanges,
    Console,
    Copy,
    CreditCard,
    Dash,
    Dashboard,
    Database,
    Debug,
    DebugAlt,
    DebugAltSmall,
    DebugBreakpoint,
    DebugBreakpointConditional,
    DebugBreakpointConditionalDisabled,
    DebugBreakpointConditionalUnverified,
    DebugBreakpointData,
    DebugBreakpointDataDisabled,
    DebugBreakpointDataUnverified,
    DebugBreakpointDisabled,
    DebugBreakpointFunction,
    DebugBreakpointFunctionDisabled,
    DebugBreakpointFunctionUnverified,
    DebugBreakpointLog,
    DebugBreakpointLogDisabled,
    DebugBreakpointLogUnverified,
    DebugBreakpointUnsupported,
    DebugBreakpointUnverified,
    DebugConsole,
    DebugContinue,
    DebugDisconnect,
    DebugHint,
    DebugPause,
    DebugRestart,
    DebugRestartFrame,
    DebugReverseContinue,
    DebugStackframe,
    DebugStackframeActive,
    DebugStackframeDot,
    DebugStackframeFocused,
    DebugStart,
    DebugStepBack,
    DebugStepInto,
    DebugStepOut,
    DebugStepOver,
    DebugStop,
    DesktopDownload,
    DeviceCamera,
    DeviceCameraVideo,
    DeviceDesktop,
    DeviceMobile,
    Diff,
    DiffAdded,
    DiffIgnored,
    DiffModified,
    DiffRemoved,
    DiffRenamed,
    Discard,
    DropDownButton,
    Edit,
    EditorLayout,
    Ellipsis,
    EmptyWindow,
    Error,
    Exclude,
    ExpandAll,
    Export,
    Extensions,
    Eye,
    EyeClosed,
    EyeUnwatch,
    EyeWatch,
    Feedback,
    File,
    FileAdd,
    FileBinary,
    FileCode,
    FileDirectory,
    FileDirectoryCreate,
    FileMedia,
    FilePdf,
    FileSubmodule,
    FileSymlinkDirectory,
    FileSymlinkFile,
    FileText,
    FileZip,
    Files,
    Filter,
    Flame,
    Fold,
    FoldDown,
    FoldUp,
    Folder,
    FolderActive,
    FolderOpened,
    Gather,
    Gear,
    Gift,
    Gist,
    GistFork,
    GistNew,
    GistPrivate,
    GistSecret,
    GitBranch,
    GitBranchCreate,
    GitBranchDelete,
    GitCommit,
    GitCompare,
    GitForkPrivate,
    GitMerge,
    GitPullRequest,
    GitPullRequestAbandoned,
    Github,
    GithubAction,
    GithubAlt,
    GithubInverted,
    Globe,
    GoToFile,
    Grabber,
    Graph,
    GraphLeft,
    Gripper,
    GroupByRefType,
    Heart,
    History,
    Home,
    HorizontalRule,
    Hubot,
    Inbox,
    Info,
    IssueClosed,
    IssueOpened,
    IssueReopened,
    Issues,
    Italic,
    Jersey,
    Json,
    KebabHorizontal,
    KebabVertical,
    Key,
    Keyboard,
    Law,
    Library,
    LightBulb,
    Lightbulb,
    LightbulbAutofix,
    Link,
    LinkExternal,
    ListFilter,
    ListFlat,
    ListOrdered,
    ListSelection,
    ListTree,
    ListUnordered,
    LiveShare,
    Loading,
    Location,
    Lock,
    LogIn,
    LogOut,
    LogoGithub,
    Magnet,
    Mail,
    MailRead,
    MailReply,
    MarkGithub,
    Markdown,
    Megaphone,
    Mention,
    Menu,
    Merge,
    Microscope,
    Milestone,
    Mirror,
    MirrorPrivate,
    MirrorPublic,
    More,
    MortarBoard,
    Move,
    MultipleWindows,
    Mute,
    NewFile,
    NewFolder,
    NoNewline,
    Note,
    Notebook,
    Octoface,
    OpenPreview,
    Organization,
    OrganizationFilled,
    OrganizationOutline,
    Output,
    Package,
    Paintcan,
    Pass,
    PassFilled,
    Pencil,
    Person,
    PersonAdd,
    PersonFilled,
    PersonFollow,
    PersonOutline,
    Pin,
    Pinned,
    PinnedDirty,
    Play,
    PlayCircle,
    Plug,
    Plus,
    PreserveCase,
    Preview,
    PrimitiveDot,
    PrimitiveSquare,
    Project,
    Pulse,
    Question,
    Quote,
    RadioTower,
    Reactions,
    Record,
    RecordKeys,
    Redo,
    References,
    Refresh,
    Regex,
    Remote,
    RemoteExplorer,
    Remove,
    RemoveClose,
    Repl,
    Replace,
    ReplaceAll,
    Reply,
    Repo,
    RepoClone,
    RepoCreate,
    RepoDelete,
    RepoForcePush,
    RepoForked,
    RepoPull,
    RepoPush,
    RepoSync,
    Report,
    RequestChanges,
    Rocket,
    RootFolder,
    RootFolderOpened,
    Rss,
    Ruby,
    Run,
    RunAll,
    Save,
    SaveAll,
    SaveAs,
    ScreenFull,
    ScreenNormal,
    Search,
    SearchSave,
    SearchStop,
    Selection,
    Server,
    ServerEnvironment,
    ServerProcess,
    Settings,
    SettingsGear,
    Shield,
    SignIn,
    SignOut,
    Smiley,
    SortPrecedence,
    SourceControl,
    SplitHorizontal,
    SplitVertical,
    Squirrel,
    Star,
    StarAdd,
    StarDelete,
    StarEmpty,
    StarFull,
    StarHalf,
    Stop,
    StopCircle,
    SymbolArray,
    SymbolBoolean,
    SymbolClass,
    SymbolColor,
    SymbolConstant,
    SymbolConstructor,
    SymbolEnum,
    SymbolEnumMember,
    SymbolEvent,
    SymbolField,
    SymbolFile,
    SymbolFolder,
    SymbolFunction,
    SymbolInterface,
    SymbolKey,
    SymbolKeyword,
    SymbolMethod,
    SymbolMisc,
    SymbolModule,
    SymbolNamespace,
    SymbolNull,
    SymbolNumber,
    SymbolNumeric,
    SymbolObject,
    SymbolOperator,
    SymbolPackage,
    SymbolParameter,
    SymbolProperty,
    SymbolReference,
    SymbolRuler,
    SymbolSnippet,
    SymbolString,
    SymbolStruct,
    SymbolStructure,
    SymbolText,
    SymbolTypeParameter,
    SymbolUnit,
    SymbolValue,
    SymbolVariable,
    Sync,
    SyncIgnored,
    Tag,
    TagAdd,
    TagRemove,
    Tasklist,
    Telescope,
    Terminal,
    TextSize,
    ThreeBars,
    Thumbsdown,
    Thumbsup,
    Tools,
    Trash,
    Trashcan,
    TriangleDown,
    TriangleLeft,
    TriangleRight,
    TriangleUp,
    Twitter,
    Unfold,
    UngroupByRefType,
    Unlock,
    Unmute,
    Unverified,
    Variable,
    Verified,
    Versions,
    Vm,
    VmActive,
    VmConnect,
    VmOutline,
    VmRunning,
    Warning,
    Watch,
    Whitespace,
    WholeWord,
    Window,
    WordWrap,
    Wrench,
    WrenchSubaction,
    X,
    Zap,
    ZoomIn,
    ZoomOut,
    WorkspaceTrusted,
}

export const iconNameMap = new Map<Codicon, string>([
    [Codicon.Account, "account"],
    [Codicon.ActivateBreakpoints, "activate-breakpoints"],
    [Codicon.Add, "add"],
    [Codicon.Alert, "alert"],
    [Codicon.Archive, "archive"],
    [Codicon.Array, "array"],
    [Codicon.ArrowBoth, "arrow-both"],
    [Codicon.ArrowDown, "arrow-down"],
    [Codicon.ArrowLeft, "arrow-left"],
    [Codicon.ArrowRight, "arrow-right"],
    [Codicon.ArrowSmallDown, "arrow-small-down"],
    [Codicon.ArrowSmallLeft, "arrow-small-left"],
    [Codicon.ArrowSmallRight, "arrow-small-right"],
    [Codicon.ArrowSmallUp, "arrow-small-up"],
    [Codicon.ArrowUp, "arrow-up"],
    [Codicon.Beaker, "beaker"],
    [Codicon.Bell, "bell"],
    [Codicon.BellDot, "bell-dot"],
    [Codicon.Bold, "bold"],
    [Codicon.Book, "book"],
    [Codicon.Bookmark, "bookmark"],
    [Codicon.Briefcase, "briefcase"],
    [Codicon.Broadcast, "broadcast"],
    [Codicon.Browser, "browser"],
    [Codicon.Bug, "bug"],
    [Codicon.Calendar, "calendar"],
    [Codicon.CallIncoming, "call-incoming"],
    [Codicon.CaseSensitive, "case-sensitive"],
    [Codicon.Check, "check"],
    [Codicon.CheckAll, "check-all"],
    [Codicon.Checklist, "checklist"],
    [Codicon.ChevronDown, "chevron-down"],
    [Codicon.ChevronLeft, "chevron-left"],
    [Codicon.ChevronRight, "chevron-right"],
    [Codicon.ChevronUp, "chevron-up"],
    [Codicon.ChromeClose, "chrome-close"],
    [Codicon.ChromeMaximize, "chrome-maximize"],
    [Codicon.ChromeMinimize, "chrome-minimize"],
    [Codicon.ChromeRestore, "chrome-restore"],
    [Codicon.CircleFilled, "circle-filled"],
    [Codicon.CircleLargeFilled, "circle-large-filled"],
    [Codicon.CircleLargeOutline, "circle-large-outline"],
    [Codicon.CircleOutline, "circle-outline"],
    [Codicon.CircleSlash, "circle-slash"],
    [Codicon.CircuitBoard, "circuit-board"],
    [Codicon.ClearAll, "clear-all"],
    [Codicon.Clippy, "clippy"],
    [Codicon.Clock, "clock"],
    [Codicon.Clone, "clone"],
    [Codicon.Close, "close"],
    [Codicon.CloseAll, "close-all"],
    [Codicon.CloseDirty, "close-dirty"],
    [Codicon.Cloud, "cloud"],
    [Codicon.CloudDownload, "cloud-download"],
    [Codicon.CloudUpload, "cloud-upload"],
    [Codicon.Code, "code"],
    [Codicon.CollapseAll, "collapse-all"],
    [Codicon.ColorMode, "color-mode"],
    [Codicon.Combine, "combine"],
    [Codicon.Comment, "comment"],
    [Codicon.CommentAdd, "comment-add"],
    [Codicon.CommentDiscussion, "comment-discussion"],
    [Codicon.CompareChanges, "compare-changes"],
    [Codicon.Console, "console"],
    [Codicon.Copy, "copy"],
    [Codicon.CreditCard, "credit-card"],
    [Codicon.Dash, "dash"],
    [Codicon.Dashboard, "dashboard"],
    [Codicon.Database, "database"],
    [Codicon.Debug, "debug"],
    [Codicon.DebugAlt, "debug-alt"],
    [Codicon.DebugAltSmall, "debugAlt-small"],
    [Codicon.DebugBreakpoint, "debug-breakpoint"],
    [Codicon.DebugBreakpointConditional, "debug-breakpoint-conditional"],
    [Codicon.DebugBreakpointConditionalDisabled, "debug-breakpoint-conditional-disabled"],
    [Codicon.DebugBreakpointConditionalUnverified, "debug-breakpoint-conditional-unverified"],
    [Codicon.DebugBreakpointData, "debug-breakpoint-data"],
    [Codicon.DebugBreakpointDataDisabled, "debug-breakpoint-data-disabled"],
    [Codicon.DebugBreakpointDataUnverified, "debug-breakpoint-data-unverified"],
    [Codicon.DebugBreakpointDisabled, "debug-breakpoint-disabled"],
    [Codicon.DebugBreakpointFunction, "debug-breakpoint-function"],
    [Codicon.DebugBreakpointFunctionDisabled, "debug-breakpoint-function-disabled"],
    [Codicon.DebugBreakpointFunctionUnverified, "debug-breakpoint-function-unverified"],
    [Codicon.DebugBreakpointLog, "debug-breakpoint-log"],
    [Codicon.DebugBreakpointLogDisabled, "debug-breakpoint-log-disabled"],
    [Codicon.DebugBreakpointLogUnverified, "debug-breakpoint-log-unverified"],
    [Codicon.DebugBreakpointUnsupported, "debug-breakpoint-unsupported"],
    [Codicon.DebugBreakpointUnverified, "debug-breakpoint-unverified"],
    [Codicon.DebugConsole, "debug-console"],
    [Codicon.DebugContinue, "debug-continue"],
    [Codicon.DebugDisconnect, "debug-disconnect"],
    [Codicon.DebugHint, "debug-hint"],
    [Codicon.DebugPause, "debug-pause"],
    [Codicon.DebugRestart, "debug-restart"],
    [Codicon.DebugRestartFrame, "debug-restart-frame"],
    [Codicon.DebugReverseContinue, "debug-reverse-continue"],
    [Codicon.DebugStackframe, "debug-stackframe"],
    [Codicon.DebugStackframeActive, "debug-stackframe-active"],
    [Codicon.DebugStackframeDot, "debug-stackframe-dot"],
    [Codicon.DebugStackframeFocused, "debug-stackframe-focused"],
    [Codicon.DebugStart, "debug-start"],
    [Codicon.DebugStepBack, "debug-step-back"],
    [Codicon.DebugStepInto, "debug-step-into"],
    [Codicon.DebugStepOut, "debug-step-out"],
    [Codicon.DebugStepOver, "debug-step-over"],
    [Codicon.DebugStop, "debug-stop"],
    [Codicon.DesktopDownload, "desktop-download"],
    [Codicon.DeviceCamera, "device-camera"],
    [Codicon.DeviceCameraVideo, "device-camera-video"],
    [Codicon.DeviceDesktop, "device-desktop"],
    [Codicon.DeviceMobile, "device-mobile"],
    [Codicon.Diff, "diff"],
    [Codicon.DiffAdded, "diff-added"],
    [Codicon.DiffIgnored, "diff-ignored"],
    [Codicon.DiffModified, "diff-modified"],
    [Codicon.DiffRemoved, "diff-removed"],
    [Codicon.DiffRenamed, "diff-renamed"],
    [Codicon.Discard, "discard"],
    [Codicon.DropDownButton, "drop-down-button"],
    [Codicon.Edit, "edit"],
    [Codicon.EditorLayout, "editor-layout"],
    [Codicon.Ellipsis, "ellipsis"],
    [Codicon.EmptyWindow, "empty-window"],
    [Codicon.Error, "error"],
    [Codicon.Exclude, "exclude"],
    [Codicon.ExpandAll, "expand-all"],
    [Codicon.Export, "export"],
    [Codicon.Extensions, "extensions"],
    [Codicon.Eye, "eye"],
    [Codicon.EyeClosed, "eye-closed"],
    [Codicon.EyeUnwatch, "eye-unwatch"],
    [Codicon.EyeWatch, "eye-watch"],
    [Codicon.Feedback, "feedback"],
    [Codicon.File, "file"],
    [Codicon.FileAdd, "file-add"],
    [Codicon.FileBinary, "file-binary"],
    [Codicon.FileCode, "file-code"],
    [Codicon.FileDirectory, "file-directory"],
    [Codicon.FileDirectoryCreate, "file-directory-create"],
    [Codicon.FileMedia, "file-media"],
    [Codicon.FilePdf, "file-pdf"],
    [Codicon.FileSubmodule, "file-submodule"],
    [Codicon.FileSymlinkDirectory, "file-symlink-directory"],
    [Codicon.FileSymlinkFile, "file-symlink-file"],
    [Codicon.FileText, "file-text"],
    [Codicon.FileZip, "file-zip"],
    [Codicon.Files, "files"],
    [Codicon.Filter, "filter"],
    [Codicon.Flame, "flame"],
    [Codicon.Fold, "fold"],
    [Codicon.FoldDown, "fold-down"],
    [Codicon.FoldUp, "fold-up"],
    [Codicon.Folder, "folder"],
    [Codicon.FolderActive, "folder-active"],
    [Codicon.FolderOpened, "folder-opened"],
    [Codicon.Gather, "gather"],
    [Codicon.Gear, "gear"],
    [Codicon.Gift, "gift"],
    [Codicon.Gist, "gist"],
    [Codicon.GistFork, "gist-fork"],
    [Codicon.GistNew, "gist-new"],
    [Codicon.GistPrivate, "gist-private"],
    [Codicon.GistSecret, "gist-secret"],
    [Codicon.GitBranch, "git-branch"],
    [Codicon.GitBranchCreate, "git-branch-create"],
    [Codicon.GitBranchDelete, "git-branch-delete"],
    [Codicon.GitCommit, "git-commit"],
    [Codicon.GitCompare, "git-compare"],
    [Codicon.GitForkPrivate, "git-fork-private"],
    [Codicon.GitMerge, "git-merge"],
    [Codicon.GitPullRequest, "git-pull-request"],
    [Codicon.GitPullRequestAbandoned, "git-pull-request-abandoned"],
    [Codicon.Github, "github"],
    [Codicon.GithubAction, "github-action"],
    [Codicon.GithubAlt, "github-alt"],
    [Codicon.GithubInverted, "github-inverted"],
    [Codicon.Globe, "globe"],
    [Codicon.GoToFile, "go-to-file"],
    [Codicon.Grabber, "grabber"],
    [Codicon.Graph, "graph"],
    [Codicon.GraphLeft, "graph-left"],
    [Codicon.Gripper, "gripper"],
    [Codicon.GroupByRefType, "group-by-ref-type"],
    [Codicon.Heart, "heart"],
    [Codicon.History, "history"],
    [Codicon.Home, "home"],
    [Codicon.HorizontalRule, "horizontal-rule"],
    [Codicon.Hubot, "hubot"],
    [Codicon.Inbox, "inbox"],
    [Codicon.Info, "info"],
    [Codicon.IssueClosed, "issue-closed"],
    [Codicon.IssueOpened, "issue-opened"],
    [Codicon.IssueReopened, "issue-reopened"],
    [Codicon.Issues, "issues"],
    [Codicon.Italic, "italic"],
    [Codicon.Jersey, "jersey"],
    [Codicon.Json, "json"],
    [Codicon.KebabHorizontal, "kebab-horizontal"],
    [Codicon.KebabVertical, "kebab-vertical"],
    [Codicon.Key, "key"],
    [Codicon.Keyboard, "keyboard"],
    [Codicon.Law, "law"],
    [Codicon.Library, "library"],
    [Codicon.LightBulb, "light-bulb"],
    [Codicon.Lightbulb, "lightbulb"],
    [Codicon.LightbulbAutofix, "lightbulb-autofix"],
    [Codicon.Link, "link"],
    [Codicon.LinkExternal, "link-external"],
    [Codicon.ListFilter, "list-filter"],
    [Codicon.ListFlat, "list-flat"],
    [Codicon.ListOrdered, "list-ordered"],
    [Codicon.ListSelection, "list-selection"],
    [Codicon.ListTree, "list-tree"],
    [Codicon.ListUnordered, "list-unordered"],
    [Codicon.LiveShare, "live-share"],
    [Codicon.Loading, "loading"],
    [Codicon.Location, "location"],
    [Codicon.Lock, "lock"],
    [Codicon.LogIn, "log-in"],
    [Codicon.LogOut, "log-out"],
    [Codicon.LogoGithub, "logo-github"],
    [Codicon.Magnet, "magnet"],
    [Codicon.Mail, "mail"],
    [Codicon.MailRead, "mail-read"],
    [Codicon.MailReply, "mail-reply"],
    [Codicon.MarkGithub, "mark-github"],
    [Codicon.Markdown, "markdown"],
    [Codicon.Megaphone, "megaphone"],
    [Codicon.Mention, "mention"],
    [Codicon.Menu, "menu"],
    [Codicon.Merge, "merge"],
    [Codicon.Microscope, "microscope"],
    [Codicon.Milestone, "milestone"],
    [Codicon.Mirror, "mirror"],
    [Codicon.MirrorPrivate, "mirror-private"],
    [Codicon.MirrorPublic, "mirror-public"],
    [Codicon.More, "more"],
    [Codicon.MortarBoard, "mortar-board"],
    [Codicon.Move, "move"],
    [Codicon.MultipleWindows, "multiple-windows"],
    [Codicon.Mute, "mute"],
    [Codicon.NewFile, "new-file"],
    [Codicon.NewFolder, "new-folder"],
    [Codicon.NoNewline, "no-newline"],
    [Codicon.Note, "note"],
    [Codicon.Notebook, "notebook"],
    [Codicon.Octoface, "octoface"],
    [Codicon.OpenPreview, "open-preview"],
    [Codicon.Organization, "organization"],
    [Codicon.OrganizationFilled, "organization-filled"],
    [Codicon.OrganizationOutline, "organization-outline"],
    [Codicon.Output, "output"],
    [Codicon.Package, "package"],
    [Codicon.Paintcan, "paintcan"],
    [Codicon.Pass, "pass"],
    [Codicon.PassFilled, "pass-filled"],
    [Codicon.Pencil, "pencil"],
    [Codicon.Person, "person"],
    [Codicon.PersonAdd, "person-add"],
    [Codicon.PersonFilled, "person-filled"],
    [Codicon.PersonFollow, "person-follow"],
    [Codicon.PersonOutline, "person-outline"],
    [Codicon.Pin, "pin"],
    [Codicon.Pinned, "pinned"],
    [Codicon.PinnedDirty, "pinned-dirty"],
    [Codicon.Play, "play"],
    [Codicon.PlayCircle, "play-circle"],
    [Codicon.Plug, "plug"],
    [Codicon.Plus, "plus"],
    [Codicon.PreserveCase, "preserve-case"],
    [Codicon.Preview, "preview"],
    [Codicon.PrimitiveDot, "primitive-dot"],
    [Codicon.PrimitiveSquare, "primitive-square"],
    [Codicon.Project, "project"],
    [Codicon.Pulse, "pulse"],
    [Codicon.Question, "question"],
    [Codicon.Quote, "quote"],
    [Codicon.RadioTower, "radio-tower"],
    [Codicon.Reactions, "reactions"],
    [Codicon.Record, "record"],
    [Codicon.RecordKeys, "record-keys"],
    [Codicon.Redo, "redo"],
    [Codicon.References, "references"],
    [Codicon.Refresh, "refresh"],
    [Codicon.Regex, "regex"],
    [Codicon.Remote, "remote"],
    [Codicon.RemoteExplorer, "remote-explorer"],
    [Codicon.Remove, "remove"],
    [Codicon.RemoveClose, "remove-close"],
    [Codicon.Repl, "repl"],
    [Codicon.Replace, "replace"],
    [Codicon.ReplaceAll, "replace-all"],
    [Codicon.Reply, "reply"],
    [Codicon.Repo, "repo"],
    [Codicon.RepoClone, "repo-clone"],
    [Codicon.RepoCreate, "repo-create"],
    [Codicon.RepoDelete, "repo-delete"],
    [Codicon.RepoForcePush, "repo-force-push"],
    [Codicon.RepoForked, "repo-forked"],
    [Codicon.RepoPull, "repo-pull"],
    [Codicon.RepoPush, "repo-push"],
    [Codicon.RepoSync, "repo-sync"],
    [Codicon.Report, "report"],
    [Codicon.RequestChanges, "request-changes"],
    [Codicon.Rocket, "rocket"],
    [Codicon.RootFolder, "root-folder"],
    [Codicon.RootFolderOpened, "root-folder-opened"],
    [Codicon.Rss, "rss"],
    [Codicon.Ruby, "ruby"],
    [Codicon.Run, "run"],
    [Codicon.RunAll, "run-all"],
    [Codicon.Save, "save"],
    [Codicon.SaveAll, "save-all"],
    [Codicon.SaveAs, "save-as"],
    [Codicon.ScreenFull, "screen-full"],
    [Codicon.ScreenNormal, "screen-normal"],
    [Codicon.Search, "search"],
    [Codicon.SearchSave, "search-save"],
    [Codicon.SearchStop, "search-stop"],
    [Codicon.Selection, "selection"],
    [Codicon.Server, "server"],
    [Codicon.ServerEnvironment, "server-environment"],
    [Codicon.ServerProcess, "server-process"],
    [Codicon.Settings, "settings"],
    [Codicon.SettingsGear, "settings-gear"],
    [Codicon.Shield, "shield"],
    [Codicon.SignIn, "sign-in"],
    [Codicon.SignOut, "sign-out"],
    [Codicon.Smiley, "smiley"],
    [Codicon.SortPrecedence, "sort-precedence"],
    [Codicon.SourceControl, "source-control"],
    [Codicon.SplitHorizontal, "split-horizontal"],
    [Codicon.SplitVertical, "split-vertical"],
    [Codicon.Squirrel, "squirrel"],
    [Codicon.Star, "star"],
    [Codicon.StarAdd, "star-add"],
    [Codicon.StarDelete, "star-delete"],
    [Codicon.StarEmpty, "star-empty"],
    [Codicon.StarFull, "star-full"],
    [Codicon.StarHalf, "star-half"],
    [Codicon.Stop, "stop"],
    [Codicon.StopCircle, "stop-circle"],
    [Codicon.SymbolArray, "symbol-array"],
    [Codicon.SymbolBoolean, "symbol-boolean"],
    [Codicon.SymbolClass, "symbol-class"],
    [Codicon.SymbolColor, "symbol-color"],
    [Codicon.SymbolConstant, "symbol-constant"],
    [Codicon.SymbolConstructor, "symbol-constructor"],
    [Codicon.SymbolEnum, "symbol-enum"],
    [Codicon.SymbolEnumMember, "symbol-enum-member"],
    [Codicon.SymbolEvent, "symbol-event"],
    [Codicon.SymbolField, "symbol-field"],
    [Codicon.SymbolFile, "symbol-file"],
    [Codicon.SymbolFolder, "symbol-folder"],
    [Codicon.SymbolFunction, "symbol-function"],
    [Codicon.SymbolInterface, "symbol-interface"],
    [Codicon.SymbolKey, "symbol-key"],
    [Codicon.SymbolKeyword, "symbol-keyword"],
    [Codicon.SymbolMethod, "symbol-method"],
    [Codicon.SymbolMisc, "symbol-misc"],
    [Codicon.SymbolModule, "symbol-module"],
    [Codicon.SymbolNamespace, "symbol-namespace"],
    [Codicon.SymbolNull, "symbol-null"],
    [Codicon.SymbolNumber, "symbol-number"],
    [Codicon.SymbolNumeric, "symbol-numeric"],
    [Codicon.SymbolObject, "symbol-object"],
    [Codicon.SymbolOperator, "symbol-operator"],
    [Codicon.SymbolPackage, "symbol-package"],
    [Codicon.SymbolParameter, "symbol-parameter"],
    [Codicon.SymbolProperty, "symbol-property"],
    [Codicon.SymbolReference, "symbol-reference"],
    [Codicon.SymbolRuler, "symbol-ruler"],
    [Codicon.SymbolSnippet, "symbol-snippet"],
    [Codicon.SymbolString, "symbol-string"],
    [Codicon.SymbolStruct, "symbol-struct"],
    [Codicon.SymbolStructure, "symbol-structure"],
    [Codicon.SymbolText, "symbol-text"],
    [Codicon.SymbolTypeParameter, "symbol-type-parameter"],
    [Codicon.SymbolUnit, "symbol-unit"],
    [Codicon.SymbolValue, "symbol-value"],
    [Codicon.SymbolVariable, "symbol-variable"],
    [Codicon.Sync, "sync"],
    [Codicon.SyncIgnored, "sync-ignored"],
    [Codicon.Tag, "tag"],
    [Codicon.TagAdd, "tag-add"],
    [Codicon.TagRemove, "tag-remove"],
    [Codicon.Tasklist, "tasklist"],
    [Codicon.Telescope, "telescope"],
    [Codicon.Terminal, "terminal"],
    [Codicon.TextSize, "text-size"],
    [Codicon.ThreeBars, "three-bars"],
    [Codicon.Thumbsdown, "thumbsdown"],
    [Codicon.Thumbsup, "thumbsup"],
    [Codicon.Tools, "tools"],
    [Codicon.Trash, "trash"],
    [Codicon.Trashcan, "trashcan"],
    [Codicon.TriangleDown, "triangle-down"],
    [Codicon.TriangleLeft, "triangle-left"],
    [Codicon.TriangleRight, "triangle-right"],
    [Codicon.TriangleUp, "triangle-up"],
    [Codicon.Twitter, "twitter"],
    [Codicon.Unfold, "unfold"],
    [Codicon.UngroupByRefType, "ungroup-by-ref-type"],
    [Codicon.Unlock, "unlock"],
    [Codicon.Unmute, "unmute"],
    [Codicon.Unverified, "unverified"],
    [Codicon.Variable, "variable"],
    [Codicon.Verified, "verified"],
    [Codicon.Versions, "versions"],
    [Codicon.Vm, "vm"],
    [Codicon.VmActive, "vm-active"],
    [Codicon.VmConnect, "vm-connect"],
    [Codicon.VmOutline, "vm-outline"],
    [Codicon.VmRunning, "vm-running"],
    [Codicon.Warning, "warning"],
    [Codicon.Watch, "watch"],
    [Codicon.Whitespace, "whitespace"],
    [Codicon.WholeWord, "whole-word"],
    [Codicon.Window, "window"],
    [Codicon.WordWrap, "word-wrap"],
    [Codicon.WorkspaceTrusted, "workspace-trusted"],
    [Codicon.Wrench, "wrench"],
    [Codicon.WrenchSubaction, "wrench-subaction"],
    [Codicon.X, "x"],
    [Codicon.Zap, "zap"],
    [Codicon.ZoomIn, "zoom-in"],
    [Codicon.ZoomOut, "zoom-out"],
]);
